name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      GO-TO-DEV:
        description: 'Deploy/Promote to Dev?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-TEST:
        description: 'Deploy/Promote to Test?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-STAGE:
        description: 'Deploy/Promote to Stage?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-DR:
        description: 'Deploy/Promote to DR?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-PROD:
        description: 'Deploy/Promote to Prod?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
jobs:
  deploy-dev:
    if: GO_TO_DEV == 'yes'
    runs-on: ubuntu-latest
    steps:
# here you would want to use AAInternal to deploy using their docker action
      - name: Build
        run: echo "building..."
        
      - name: Deploy
        run: echo "deploying to dev...done"
        
  deploy-test:
    if: GO_TO_TEST == 'yes'
    runs-on: ubuntu-latest
    steps:
# here you would want to use AAInternal to deploy using their docker action
      - name: Build
        run: echo "building..."
        
      - name: Deploy
        run: echo "deploying to test...done"
  
  deploy-stage:
    if: GO_TO_STAGE == 'yes'
    runs-on: ubuntu-latest
    steps:
# here you would want to use AAInternal to deploy using their docker action
      - name: Build
        run: echo "building..."
        
      - name: Deploy
        run: echo "deploying to stage...done"
        
  deploy-dr:
    if: GO_TO_DR == 'yes'
    runs-on: ubuntu-latest
    steps:
# here you would want to use AAInternal to deploy using their docker action
      - name: Build
        run: echo "building..."
        
      - name: Deploy
        run: echo "deploying to DR...done"
        
  deploy-prod:
    if: GO_TO_PROD == 'yes'
    runs-on: ubuntu-latest
    steps:
# here you would want to use AAInternal to deploy using their docker action
      - name: Build
        run: echo "building..."
        
      - name: Deploy
        run: echo "deploying to prod...done"
