name: First Workflow
on: 
  workflow_dispatch:
    inputs:
      GO-TO-DEV:
        description: 'Deploy/Promote to Dev?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-TEST:
        description: 'Deploy/Promote to Test?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-STAGE:
        description: 'Deploy/Promote to Stage?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-DR:
        description: 'Deploy/Promote to DR?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
      GO-TO-PROD:
        description: 'Deploy/Promote to Prod?'
        required: true
        default: 'no'
        options:
          - 'yes'
          - 'no'
jobs:
  - uses: gh-first-action/gh-first-action/.github/workflows/deploy-test.yml@main
    with:
      GO-TO-DEV: ${{ github.events.inputs.GO-TO-DEV }}